### ISSUE TITLE
Dynamic Folder for Netbox

### ISSUE THREAD

**Issue by Yannick246** [royalapplications/toolbox#101]
Hello everyone,

has anyone ever tried a connector for Netbox? This would probably make data maintenance in RoyalTS easier for many people/companies.

One idea would be a dynamic folder that automatically loads the devices according to tenants (in Netbox this is the wording for customers) by sites or groups in RoyalTS.

Best regards
Yannick

**Comment by StefanKoell** [comment]
Hi Yannick,

we don't have any experience with Netbox but from the docs it seems there's a REST API which can be consumed. It might be a good idea to post in their github discussion:
https://github.com/netbox-community/netbox/discussions

Maybe one of the Netbox contributors, is also a Royal TS user and is interested in an integration via dynamic folder.

Regards,
Stefan
