### ISSUE TITLE
color in applescript

### ISSUE THREAD

**Issue by lavinnyv** [royalapplications/toolbox#111]
in the moreautomation.scpt sample, what if i wanted to add - color "#800000" - i keep getting an error trying to add this. "expected end of line, etc. but found property"

i've tried with out the hash in front of the number

**Comment by GermarT** [comment]
Hi,
you can define the color using the following command:
set property value

The property that you have to set is called “Color”. Based on what you have written, the following should work for you:
set property value of key "Color" of id newConId1 to "#800000"

To clarify, the ID is saved in the variable "newConId1". I hope this helps!

**Comment by lavinnyv** [comment]
works amazing!

thank you!
