### ISSUE TITLE
Secret Server - Secrets not working

### ISSUE THREAD

**Issue by Ramadel** [royalapplications/toolbox#13]
When using the dynamic folder (powershell) to connect to Thycotic Secret Server, it works in populating it. It even works with Duo (though we are restricted to using our tokens.) However, when actually trying to use the credentials on, say, an RDP connection, I get the following error: 

> Error: Resolving dynamic credential data failed: Unexpected character encountered while parsing value: G. Path '', line 0, position 0.

I get prompted for the OTP pin as usual, but this is all I get afterwards. It sounds like an error in the script code somewhere, but I have no clue where.

![Error](https://user-images.githubusercontent.com/54110249/63028024-ff994380-be7b-11e9-9a40-8f6c4889b503.PNG)

**Comment by lemonmojo** [comment]
Hi @Ramadel,

the best way to debug issues like these is to copy the responsible script into a separate file, replace all tokens with actual values and try running it directly outside of Royal TS.
Please try this and let us know what error message you're receiving.

thx,
felix

**Comment by Ramadel** [comment]
I'm not sure I follow. The folder script populates the folder correctly; it's the Dynamic Credential Script that doesn't work. What tokens are you referring to? I see many things having to do with the $restricted variable. Is that what you're talking about?

**Comment by lemonmojo** [comment]
I understood that it's only the dynamic credential script that's failing for you. Still, the best option is to just copy the contents of the script from the "Dynamic Credential Script" section of your Dynamic Folder and paste it in a new PowerShell file. Then, replace the tokens in the last line of the script (`$CustomProperty.ServerURL$`, `"$EffectiveUsername$"`, etc.) with real values and run it.

Regarding `"$DynamicCredential.EffectiveID$"`: That's the ID of the credential stored in your Secret Server instance that will get resolved when a connection referencing this ID is opened. So for testing you can use any of your Secret Server credential's ID's.

Hope that helps!

**Comment by Ramadel** [comment]
OK, I tested it that way, and it retrieves the credentials fine, but I still get the above error from RoyalTS.

**Comment by StefanKoell** [comment]
Can you post the JSON output when you manually execute the dynamic credential script (without the sensitive information, of course)?

Also, when you look at the password in the json output, are there any characters in it which could break the json? The parser shouldn't allow that, just double-checking...

**Comment by Ramadel** [comment]
Here's the same output of two different secrets, obfuscated, but showing special characters that may mess up JSON (I don't know what would)...

```
{
    "Username":  "hunter\\Admin.Benedict",
    "Passphrase":  "",
    "Password":  "Df23sdf:2f-3345"
}
```

```
{
    "Username":  "root",
    "Passphrase":  "",
    "Password":  "DesD}rS)3d$@E-"
}
```

**Comment by StefanKoell** [comment]
I'm a bit confused. How do you get the json output for the dynamic credential when the script fails? Is this error thrown all the time or just sometimes?

Also, can you try to remote the -Method POST from the command and see if that works. I looked at the samples here https://thycotic.force.com/support/s/article/REST-API-PowerShell-Scripts-Getting-Started and it seems they do not use POST

**Comment by StefanKoell** [comment]
My colleague just tested the scripts and they are working with 10.6. What version are you running?

Also, when running the Invoke-WebRequest manually, make sure $api and $secretID is set correctly.

**Comment by Ramadel** [comment]
Oops, my mistake. I wasn't populating $SecretID. When I do that now, with a valid number, the script works fine.

I still get the error in RoyalTS itself however.

**Comment by StefanKoell** [comment]
My colleague tested the scripts on Royal TSX for macOS and there it's working fine. I just debugged through the Windows version and while still most of the code regarding dynamic credentials is shared, there is a but in the Windows version which is causing the error.

I was able to fix it for the next release.

So to sum up:
The script is working.
Royal TS for Windows has a bug preventing dynamic credentials to be parsed correctly.

A new beta release should be available in the next week or so.

I'm really sorry for the inconvenience.

**Comment by Ramadel** [comment]
No problem. Just glad to know you're willing to follow up. :)

**Comment by StefanKoell** [comment]
I've done some tests. You will get this kind of error if you by mistake download the .rdfe file from github as HTML (when you click on the .rdfe file and click on Save link as). You need to click on the file and right-click the "Raw" button to download the .rdfe correctly.

The successful message afterwards is a bug and has been fixed.

We're also working on a better import experience directly from within the app. No need to browse to github anymore with the next release...

**Comment by StefanKoell** [comment]
The last commit from Felix didn't change anything there:
https://github.com/royalapplications/toolbox/commit/3a0f09d0a17c27e9a6947139a85dd44bb399443c

Not sure why you had to tweak this for the new folder script. Did you change something on your system?

**Comment by tunnelofsludge** [comment]
I also had to remove the -SkipCertificateCheck from both the folder and credentials scripts and they worked.
