### ISSUE TITLE
Required property 'Name' expects a value but got null. Path '[0]',

### ISSUE THREAD

**Issue by zitzman** [royalapplications/toolbox#16]
Bitwarden supports having custom properties with null name but with value.
Rotal-TS dynamic Folder does not. Maybe populate the JSON with a placeholder for those so reloading folder content won't break.

**Comment by lemonmojo** [comment]
@zitzman I just fixed this in https://github.com/royalapplications/toolbox/commit/f2691d4780f2b5dcc61becc67e8d6cddaa1a810d.
Thx for the bug report!
