### ISSUE TITLE
Secret Server Integration not working through RTS

### ISSUE THREAD

**Issue by mrkoller** [royalapplications/toolbox#21]
Similar to issue #13 I am getting the error on the dynamic folder. "An error occurred while parsing the output of a dynamic folder's script: Unexpected character encountered while parsing value: C. Path ", line 0, position 0."
![image](https://user-images.githubusercontent.com/56844111/90037311-aed44a80-dc89-11ea-9f1d-899f13ac95e8.png)

I am running RTS v5.3.60720 and SS v10.7.

Running the code outside of RTS works fine for both the Folder and Credential script. The only thing I have done is removed the -skipcertificatecheck as I'm running PS 5.1 

I have tried using the built-in and manually downloading/importing the rdfe file. I'm sure there is something simple I'm missing here, but any info would be helpful.

**Comment by StefanKoell** [comment]
Hi,

you mentioned the script runs fine outside of Royal TS. Can you check the output of that script. It's very important that the script output only contains the json. Any other output / text will mess up the result.

**Comment by mrkoller** [comment]
Thanks for the reply. It certainly seems like it, but I could be missing something. Below is the sanitized output for both the folder and credentials script.

For the folder script:
{
    "Objects":  [
                    {
                        "Path":  "\\Team Folders\\Path3\\Path2 \name Power BI\\Power BI: Local Service Accounts",
                        "Name":  " domain\\username",
                        "ID":  12324,
                        "Type":  "DynamicCredential"
                    },
                    {
                        "Path":  "\\Path3\\Path2\\Path1",
                        "Name":  " other name  ",
                        "ID":  12345,
                        "Type":  "DynamicCredential"
                    },
					-----------Break------------
					{
                        "Path":  "\\Team Folders\\path2\\Server\\SQL_Int",
                        "Name":  "domain\\username1",
                        "ID":  34567,
                        "Type":  "DynamicCredential"
                    },
                    {
                        "Path":  "\\Team Folders\\path2\\Server\\SQL_Prod",
                        "Name":  "domain\\username3",
                        "ID":  56789,
                        "Type":  "DynamicCredential"
                    }
                ]
}


And for the credential script:
{
    "Username":  "username",
    "KeyFilePassphrase":  "",
    "Password":  "password"
}

**Comment by StefanKoell** [comment]
Are you sure this is the only output of your powershell script? Keep in mind that any output caused by loading the profile or anything before or after the script output will mess up the result.

**Comment by mrkoller** [comment]
That was the clue I needed. When the code ran in ISE it does not load the profile and someone edited the global profile on the server I was using for some odd reason. The checkbox to not load the profile was the ticket. Thanks very much.
