### ISSUE TITLE
Unable to set UseMultiMon via RoyalJSON

### ISSUE THREAD

**Issue by patbennett** [royalapplications/toolbox#25]
Would like to be able to set Use Multiple Monitors via Dynamic Folder script. Tried to define "UseMultiMon" object property, but it does not reflect in the object created. 
```
{
    "Objects":  [
                    {
                        "ComputerName":  "Server01",
                        "ConsoleSession":  "true",
                        "Name":  "Server01",
                        "Type":  "RemoteDesktopConnection",
                        "Path":  "Servers",
                        "WindowMode": "FullScreen",
                        "UseMultiMon":  "true"
                    }
                ]
}
```

**Comment by lemonmojo** [comment]
Hi @patbennett!

Only a small subset of the supported properties (the most common ones) is exposed directly through rJSON.

However, you can still configure other properties using the technique described in the "Advanced Scenarios" section of the documentation: https://royalapps.com/go/rjson-documentation

Please let us know if that helps or if you need additional guidance.

Cheers,
Felix

**Comment by patbennett** [comment]
Felix,

Thanks for pointing me in the right direction, was able to get it sorted out.

-Patrick

**Comment by lemonmojo** [comment]
@patbennett Perfect! Glad I could help!

Cheers,
Felix
