### ISSUE TITLE
1Password dynamic script doesn't support OTP

### ISSUE THREAD

**Issue by rfoust** [royalapplications/toolbox#34]
Looks like 1Password 8 isn't supported in TSX, so I tried using the dynamic script, but it doesn't support authenticating using a OTP. Would love to have this support added so that I can use it.  Thanks!

<img width="262" alt="Screen Shot 2022-03-11 at 9 28 19 AM" src="https://user-images.githubusercontent.com/2991296/157886721-727efcc8-08d0-48d8-b971-6a12414134a4.png">

**Comment by lemonmojo** [comment]
@rfoust We're currently working on Multi-Factor-Authentication support for the 1Password Dynamic Folder script.
Would you be interested in testing a beta version of the script?

**Comment by rfoust** [comment]
@lemonmojo Absolutely! Let me know how to get it. Thanks!

**Comment by lemonmojo** [comment]
@rfoust 

Here's the first Beta version with support for MFA-enabled 1Password accounts:

[1Password (Python) 1.1.0 BETA 1.rdfe.zip](https://github.com/royalapplications/toolbox/files/8247430/1Password.Python.1.1.0.BETA.1.rdfe.zip)

Here's how to add the Dynamic Folder to one of your documents:
- Extract the zip file
- In Royal TSX select a folder or document where you want the Dynamic Folder to be imported to
- Go to `File - Import - Dynamic Folder`
- Click `Browse…`
- Select the extracted .rdfe file (`1Password (Python) 1.1.0 BETA 1.rdfe`)
- When the properties of the Dynamic Folder open, configure your 1Password account details like previously in the `Custom Properties` section

Please note that you will have to install the [pexpect](https://pexpect.readthedocs.io/en/stable/) Python package if you're using macOS or the [wexpect](https://wexpect.readthedocs.io/en/latest/) package on Windows for this to work.

When you refresh the dynamic folder you should get prompted for your MFA code in a dialog like this:

<img width="532" alt="Screenshot 2022-03-14 at 20 07 42" src="https://user-images.githubusercontent.com/186198/158234307-3a18f149-3889-43d0-ae5d-82a33143d9e3.png">

Feedback is obviously very welcome! 😉

**Comment by rfoust** [comment]
Took me a sec to figure out how to install pexpect, but this worked (on mac) from a shell prompt:   "python3 -m pip install pexpect"

Otherwise I had no problems getting it to work, OTP worked fine.  I'll post back here if I run into any problems. Thanks!

**Comment by lemonmojo** [comment]
@rfoust Great to hear it's working for you!

**Comment by lemonmojo** [comment]
@rfoust Here's a new beta version with a couple of improvements and fixes. Could you please give this new version a try and let me know if everything still works as expected for you? Thx!

[1Password (Python) 2.0.0 BETA 5.rdfe.zip](https://github.com/royalapplications/toolbox/files/8289204/1Password.Python.2.0.0.BETA.5.rdfe.zip)

**Comment by rfoust** [comment]
So far 2.0 beta 5 is working fine.  Just a few comments:

- The default text for "Email Address" under custom properties is "TODO".  Might want to change that to something like "<Insert valid 1Password login email address here>" (or whatever)
- When the OTP popup appears, it would be helpful to have the dialog box show the email address (login) of the account that is requesting the OTP. Since I have multiple 1Password accounts, that would make it clear which one is asking for it.
- Having an upgrade/replace option for the dynamic folder script import would be nice, otherwise I have to create a new dynamic folder, and then all of the references to passwords in those folders will be broken since they're pointing to the old dynamic folder. This would make future updates a lot easier.

Hope this helps!

-Robbie

**Comment by lemonmojo** [comment]
Hey @rfoust! Thx for the feedback.

Here's a new version which includes the email address in the MFA prompt:
[1Password (Python) 2.0.0 BETA 6.rdfe.zip](https://github.com/royalapplications/toolbox/files/8308843/1Password.Python.2.0.0.BETA.6.rdfe.zip)

Regarding your other points:
* The default text for fields to be filled by the user is always "TODO". That happens automatically when exporting Dynamic Folders with "Anonymize Custom Properties" enabled. For now we will keep it like that because it's consistent in all dynamic folder samples in our repository.
* Regarding upgrading dynamic folders: That's something we will look into in the next major version of Royal TS/X. We're aware that there's room for improvement in that area but making a smooth update experience requires a couple of major changes to the way we handle dynamic folder exports/imports.

Cheers,
Felix

**Comment by lemonmojo** [comment]
I'm happy to report that we [just published](https://github.com/royalapplications/toolbox/commit/ed508f3dd0d40bf78d9a80b781b2ac2178ba39ab) version 2.0.0 of the 1Password dynamic folder sample and it's now available to import through the in-app Dynamic Folder gallery.

## Change Log

### Improvements:
* Support for two-factor authentication
* Support for private key files (new type in 1Password 8)

### Bugfixes:
* Improved error handling

### Dependency changes:
* pexpect is now required on macOS (can be installed using pip)
* wexpect is now required on Windows (can be installed using pip)

**Comment by rfoust** [comment]
Ran into a weird issue when testing this, even though it's not directly related to OTP, figured I'd mention it.  When I imported the new script in a new dynamic folder, I then deleted the older versions of the dynamic folders that I had been using.  After deleting the old ones, I was unable to save the rtsz document, I got the following error:

<img width="268" alt="Screen Shot 2022-03-22 at 9 29 50 AM" src="https://user-images.githubusercontent.com/2991296/159493757-144f48d1-138c-4034-a8ee-f8db34d997ec.png">

I was able to fix it by editing the 2 rdp session credentials to point to the new dynamic folder location, and then I was able to save the document.  Not sure what was preventing it from saving, but fixing the problem there might be the best solution, since if the credential source disappears, it just shows up as "unknown credential".

**Comment by rfoust** [comment]
Did some more testing, it seems to just be the act of deleting the dynamic folder and then immediately trying to save the document that results in the error.  Doesn't have anything to do with referencing credentials in it.  

If I wait another 10 seconds or so, the save works fine.  I wonder if there's a background task that is deleting all of the credentials in the folder that hasn't completed yet when I'm trying to save (just guessing)? If I create a 1password dynamic folder and don't actually do a refresh (so that the folder remains empty), and then delete the folder, the error doesn't occur.

**Comment by lemonmojo** [comment]
@rfoust Thx for the bug report. We just fixed this and the issue should be resolved in the next version.
