### ISSUE TITLE
Limit which 1Password vaults are imported

### ISSUE THREAD

**Issue by dstamen** [royalapplications/toolbox#42]
i would like to only import 1 vault, but it imports all. can it be limited?

**Comment by lemonmojo** [comment]
@dstamen We just pushed an update to the 1Password Dynamic Folder script which includes support for specifying a single vault to import in the "Filter" section of the "Custom Properties".
Please let me know if this works for you!

**Comment by dstamen** [comment]
Awesome! I will test and let you know.

**Comment by dstamen** [comment]
works perfect thanks!

**Comment by lemonmojo** [comment]
@dstamen 😎 thx for letting me know!
