### ISSUE TITLE
1password dynamic folder - MFA

### ISSUE THREAD

**Issue by dstamen** [royalapplications/toolbox#44]
Any chance to save passwords or have them accessible without having to enter a MFA every time its used or attempted to reconnect?

**Comment by lemonmojo** [comment]
@dstamen I just [pushed an update](https://github.com/royalapplications/toolbox/commit/b2a194db3f0b64ad78d90b9b12816394b02866ab) to the 1Password dynamic folder script which includes an option to disable creating dynamic credentials.

Please note that we absolutely don't(!) recommend using this unless you have very few items stored in 1Password. Here's an excerpt from the notes of the updated script:

> While you can instruct the script to import regular credentials (by setting the "Dynamic Credentials" setting in the "Custom Properties" section to "No", it's not(!) recommended to do so as it has many downsides. For instance, it will take much longer to retrieve all items because a web request to 1Password's web service will need to be made for each individual item. 1Password also enforces API rate limits, so if you have a lot of items, you might not be able to retrieve all of them before hitting the rate limit.

Hope this helps nonetheless!

**Comment by dstamen** [comment]
Thank you! super quick again.
