### ISSUE TITLE
Dynamic Folder / 1Password (Python) - Multiuser Document

### ISSUE THREAD

**Issue by s3-schneider** [royalapplications/toolbox#48]
It seems that the 1Password script does not work with multiple users and synced documents (for example OneDrive).
If using a dynamic folder per user and saving a login for a connection (for example RDP) or folder, it displays as unknown for other users even if they have access to the same 1Password vault.

We also did a test with the same dynamic folder document and 1Password credentials for multiple users but the behavior did not change.

I guess the internal ID for each login is created during initial load which leads to different IDs on different devices.

Maybe this is helpful: 
We were using the Bitwarden Python script until end of last year and did not have this issue.

Thanks,
Stefan

**Comment by lemonmojo** [comment]
@s3-schneider Hi Stefan! Yes, we recommend assigning credentials from Dynamic Folders using the "Specify a credential name" mode instead of "Use an existing credential".

That way, the credential is referred to by its name instead of its ID, which, as you noticed may change between reloads and among users.

Hope that helps!

Cheers,
Felix

**Comment by lemonmojo** [comment]
@s3-schneider Hi Stefan,

Bitwarden and 1Password differ in a major way when it comes to identifying the credentials stored in their systems.
Bitwarden uses GUIDs to uniquely identify credentials which happens to be the same mechanism we use in our apps. So, as long as there's no conflict with existing objects in your documents, we can use the IDs returned from Bitwarden directly and thus, they stay consistent between reloads of the dynamic folder. 1Password uses a different system which means we have to convert their IDs to GUIDs. This leads to different users getting different IDs and reloads of the dynamic folder also loosing these mappings.

Unfortunately there's not a lot we can do in that situation.

However, I can see us improving the usability of the credential picker when using the "Specify a credential name" mode. Would it be sufficient in your environment if we could provide a similar experience when selecting credentials by name as we currently have when selecting credentials by ID?

If yes, please file a feature request in our ["Ideas" forum over here](https://www.royalapps.com/go/feature-request-ts-mac) and we'll look into it.

Hope that helps!

cheers,
felix

**Comment by s3-schneider** [comment]
Hi Felix,
That's unfortunate but I understand that you can't change this / do not have control over it.

The Improvement to the credential picker for "Specify a credential name" would be great. 
Our current problem is only the usability with "Specify a credential name" due to our large count of credentials but I think that your initial solution is already viable for everyone who does not have that many.

I will file the feature request and reference to this git issue.

Best Regards,
Stefan

**Comment by lemonmojo** [comment]
@s3-schneider Thx for the feature request, Stefan. I'm closing this issue now and will continue the discussion on the support forums.
