### ISSUE TITLE
1Password | Error while signing in: EOF flag has been raised. | Win 22H2 22621.819 | Python 3.11.0 | Royal TS 7.0.11108

### ISSUE THREAD

**Issue by DRNGx** [royalapplications/toolbox#57]
Hi, 

i try to use the Dynamic Folder LOG:

`11/12/2022 7:13:39 PM - Information - Edit - The Dynamic Folder 1Password (Python) was modified.
11/12/2022 7:13:43 PM - Error - Store - An error occurred while executing the dynamic folder's script - Details:
  Error while signing in: EOF flag has been raised.
11/12/2022 7:13:43 PM - Debug - Application - [VerifyFormPosition] Warning WindowState: Normal
11/12/2022 7:13:43 PM - Debug - Application - [VerifyFormPosition] Warning Bounds: [X: 2557; Y: 447; Width: 646; Height: 138]
`

**Comment by DRNGx** [comment]
seems like it has todo with the royal ts 7 beta. with v6 its working fine

**Comment by st9rm1337** [comment]
> seems like it has todo with the royal ts 7 beta. with v6 its working fine

hi @DRNGx.
I'm from the Royal Apps support team and tried reproducing the issue on a VM several times with and without MFA, running the latest version of the Royal TS V7 beta (7.0.11108). Unfortunately, I was not able to reproduce the problem, and the script reloaded properly.
May I ask which version of the 1Password Dynamic Folder script you are using, as I tested this with the latest one from our gallery (2.0.5), and if you could try reimporting it to see if this resolves the issue?

**Comment by DRNGx** [comment]
> > seems like it has todo with the royal ts 7 beta. with v6 its working fine
> 
> hi @DRNGx. I'm from the Royal Apps support team and tried reproducing the issue on a VM several times with and without MFA, running the latest version of the Royal TS V7 beta (7.0.11108). Unfortunately, I was not able to reproduce the problem, and the script reloaded properly. May I ask which version of the 1Password Dynamic Folder script you are using, as I tested this with the latest one from our gallery (2.0.5), and if you could try reimporting it to see if this resolves the issue?

Case Closed, seems like i did something multiple times wrong while i was reproducing it. it worked this time. anyway thanks for your help!

**Comment by st9rm1337** [comment]
> > > seems like it has todo with the royal ts 7 beta. with v6 its working fine
> > 
> > 
> > hi @DRNGx. I'm from the Royal Apps support team and tried reproducing the issue on a VM several times with and without MFA, running the latest version of the Royal TS V7 beta (7.0.11108). Unfortunately, I was not able to reproduce the problem, and the script reloaded properly. May I ask which version of the 1Password Dynamic Folder script you are using, as I tested this with the latest one from our gallery (2.0.5), and if you could try reimporting it to see if this resolves the issue?
> 
> Case Closed, seems like i did something multiple times wrong while i was reproducing it. it worked this time. anyway thanks for your help!

perfect, thanks for the follow-up!
