### ISSUE TITLE
Feature Request: rJson - Windows Support

### ISSUE THREAD

**Issue by nicovs** [royalapplications/toolbox#58]
Hi, 

we've created an easy script to parse some API's, and render several json files using jq and j2cli.
This way's it's easier to maintain our RoyalTS configs than using the Powershell libs. 
The problem now is: we are half on Mac, half on Windows...Windows saddly doesnt support rjson so far

Would it be possible to support rJSON on Windows ?

Ty!
Nico

**Comment by StefanKoell** [comment]
Hi Nico,

can you check out the latest release:
https://www.royalapps.com/go/kb-ts-win-v6-releasenotes

It has the capability to open/import rjson files directly.

Regards,
Stefan

**Comment by nicovs** [comment]
Hi Stefan,

Ty for replying and of course adding the feature... One thing though:
- when opening the Rjson file, it imports it, creating a  "New Document"
- can also edit this new document on windows, where on my Mac I cannot as it is dynamic

![CleanShot 2023-02-22 at 12 05 09@2x](https://user-images.githubusercontent.com/1900299/220602466-8c9b2845-1e89-48ed-9c2e-964a674b2bc1.png)

Thanks
Nico

**Comment by StefanKoell** [comment]
Hi Nico,

thanks for getting back to us. There was indeed something missing. I have fixed the code base on Windows and it will behave the same way as on the Mac:
- Opening a rjson file using File -> Open will create a "dynamic document" (just like on Mac OS). This means the file/objects cannot be edited but you can right-click and hit reload to get the most recent content loaded up.
- If you want to edit the document/objects, you can save that document as a .rtsz file
- You can still import .rjson into a target folder using Data -> Import. In this case it will be part of the existing document. Editing objects will work right away.

The next minor release/beta release will have these fixes implemented.

Regards,
Stefan
