### ISSUE TITLE
StartProgram not being taken into consideration.

### ISSUE THREAD

**Issue by Aaouad123** [royalapplications/toolbox#64]
Hello,

We're trying to dynamically add RDP connections using a dynamic folder, however since we use a PSM connection we need to define the "StartProgram" field. Our RDP connections are created correctly and all fields are correctly filled except the advanced -> Program (property name $StartProgram$) is not being filled and will stay blank.
We are using a Python script following the examples and this is each connection:
`connection = {
            "Type": "RemoteDesktopConnection",
            "Name": "{} {} FRONT serious {} {}".format(product,cia,seriousHost,version),
            "ComputerName": psmLink,
            "Description" : sirius,
            "StartProgram" : "psm /u {} /a {} /c PSM-RDP".format(User,serious),
            "Path" : "{}/{}".format(environment,cia),
            "CredentialsFromParent" : "true"
        }
connections.append(connection)
`
we're running the above in a loop and doing this at the end of the script:
`store = {
    "Objects": connections
}
print(json.dumps(store))`

We can't seem to figure out why it's not being filled.
Your help is appreciated Thank you.

Royal TS version 6.1.50425

**Comment by lemonmojo** [comment]
Hi @Aaouad123,

`StartProgram` is not a property currently supported by our RoyalJSON data model. Please see the [documentation for RoyalJSONObject](https://docs.royalapps.com/r2021/scripting/rjson/available-properties/royaljsonobject.html) for all supported properties.

You can however still configure properties that are not directly supported by rJSON using the [technique described here](https://docs.royalapps.com/r2021/scripting/rjson/advanced-scenarios.html).

In this particular case you're looking for [this property](https://docs.royalapps.com/r2021/scripting/objects/connections/royalrdsconnection.html#startprogram) and here's your original code adapted to work with that property:

```
connection = { 
	"Type": "RemoteDesktopConnection",
	"Name": "{} {} FRONT serious {} {}".format(product,cia,seriousHost,version),
	"ComputerName": psmLink,
	"Description" : sirius,
	"Properties": {
		"StartProgram" : "psm /u {} /a {} /c PSM-RDP".format(User,serious)
	},
	"Path" : "{}/{}".format(environment,cia),
	"CredentialsFromParent" : "true"
}

connections.append(connection)
```

Hope that helps!

cheers,
Felix

**Comment by Aaouad123** [comment]
Thanks Felix,

That worked perfectly! Guess we missed that in the docs.
