### ISSUE TITLE
Secret Server Credential Objects

### ISSUE THREAD

**Issue by Nyber** [royalapplications/toolbox#85]
The Secret Server automation creates the folder and credential objects sucessfully but does not assign username and passwords inside those credential objects.

**Comment by StefanKoell** [comment]
This is by design because there is a dynamic credential script attached to the dynamic folder. This means that the credentials are only queried from the backend when it is used in order to connect to a connection.

**Comment by Nyber** [comment]
Thanks Stefan, that makes sense!  The only issue I'm having is it doesn't pull my Personal Folder.
