### ISSUE TITLE
Connecting to Thycotic

### ISSUE THREAD

**Issue by MynMac** [royalapplications/toolbox#9]
I hope this is the correct place to ask this. :-)

I'm not sure if this is actually just something on my Thycotic setup causing this but any guidance on how to see the results of what is returned by the Powershell script when it connects to my Thycotic server would be helpful.

I get the following error after login and MFA completed.

An error occurred while parsing the output of a dynamic folder's script: Unexpected character encountered while parsing value: R. Path '', line 1, position 1041.

thanks

Mynard

**Comment by patschi** [comment]
Hi,

might it be possible that you're having a custom `Microsoft.PowerShell_profile.ps1` within your `MyDocuments` folder? If so, can you rename it and try once again?

Regards,
Patrik

**Comment by lemonmojo** [comment]
@MynMac The best way to debug such issues is to save the script to disk, replace all tokens (everything that's enclosed in `$`) with actual values, then execute the script and send us the output in a new [support ticket](https://www.royalapplications.com/go/support-ticket-new).

You definitely don't want to post the output here on Github as it may contain sensitive information!

**Comment by MynMac** [comment]
Thanks for the quick response Patrik.

I'm using the extension on OSX, so I suppose that adds to the challenges as well.
My RoyalTSX has all the most recent updates and I installed the latest PowerShell (6.2.0) available for Mac.

or are you maybe referring to the folder on the Thycotic Server?

Regards,
Mynard

**Comment by MynMac** [comment]
> @MynMac The best way to debug such issues is to save the script to disk, replace all tokens (everything that's enclosed in `$`) with actual values, then execute the script and send us the output in a new [support ticket](https://www.royalapplications.com/go/support-ticket-new).
> 
> You definitely don't want to post the output here on Github as it may contain sensitive information!

Thanks Felix,

Let me attempt that as well.
Much Appreciated

Regards,
Mynard

**Comment by patschi** [comment]
> I'm using the extension on OSX, so I suppose that adds to the challenges as well.

Ah, I see! I thought you're running Royal TS on Windows. We had a few tickets with similar error message, where the `Microsoft.PowerShell_profile.ps1` file was interferencing when the script gets executed. Then please do the steps as recommended by my colleague @lemonmojo and drop us a support ticket afterwards. Thanks!

**Comment by patschi** [comment]
The issue was that on slower connections PowerShell showed a interactive progressbar, what causes our DynamicFolder-parser to fail. This was solved by commit 935f62866e8027510c3f5c6cba739c9c3bdb54dd by prepending `$ProgressPreference='SilentlyContinue'`.

Internal ref: 16922
