### ISSUE TITLE
Dynamic folder, PrivateKeyContent not work

### ISSUE THREAD

**Issue by hostadminonline1** [royalapplications/toolbox#91]
Hello 

royal tsx version 5.1.2

i'm set credentials

`{"Objects":[{"Type":"Credential","Name":"id125","Username":"root","PrivateKeyMode":1,"PrivateKeyContent":"45;45;45;45;45;66;69;71;73;78;32;79;80;69;78;83;83;72;32;80;82;73;86;65;84;69;32;75;69;89;45;45;45;45;45;10;98;51;66;108;98;110;78;122;97;67;49;114;90;88;107;116;100;106;69;65;65;65;65;65;66;71;53;118;98;109;85;65;65;65;65;69;98;109;57;117;90;81;65;65;65;65;65;65;65;65;65;66;65;65;65;67;70;119;65;65;65;65;100;122;99;50;103;116;99;110;10;78;104;65;65;65;65;65;119;69;65;65;81;65;65;65;103;69;65;116;118;121;80;73;68;80;120;115;107;108;120;117;50;83;113;49;54;76;88;50;113;48;54;85;73;122;77;114;67;81;89;54;113;122;106;50;98;118;66;106;49;81;97;116;100;69;83;120;122;80;117;10;97;103;88;65;68;71;52;55;119;84;108;70;101;117;65;43;80;78;104;105;72;75;106;122;88;119;107;43;119;115;49;108;47;67;79;68;43;110;82;75;80;54;109;50;106;69;120;114;87;68;106;120;68;89;54;116;65;102;114;65;65;83;100;56;88;119;43;85;106;119;10;115;75;105;80;78;57;89;48;88;75;116;109;107;118;76;47;56;74;54;52;76;67;69;89;98;108;74;121;50;98;78;106;90;70;120;103;85;119;49;118;49;74;72;105;73;113;54;76;88;70;69;65;101;106;81;110;67;79;69;87;101;83;101;84;104;88;75;76;72;49;10;47;48;84;120;87;48;70;101;106;72;117;99;115;110;68;85;43;114;84;79;74;89;69;107;72;89;51;77;50;113;90;104;72;49;108;114;122;72;80;53;115;89;110;120;107;51;106;55;85;117;53;111;68;71;51;115;54;43;72;116;52;48;76;52;80;101;99;101;50;76;10;112;105;107;99;51;74;82;53;43;68;68;99;47;121;102;87;73;101;74;105;103;118;107;57;119;82;90;85;112;72;54;121;82;51;74;76;90;56;43;80;69;103;112;81;100;43;108;65;56;66;47;113;88;66;65;90;43;84;70;106;43;97;55;109;69;100;76;87;100;48;10;107;102;47;87;48;114;104;102;85;103;104;49;90;110;43;56;84;50;108;65;74;72;49;110;108;97;66;109;74;72;69;106;53;119;104;72;102;118;82;110;68;119;47;116;47;101;87;121;97;98;100;90;53;116;48;57;116;85;119;75;119;111;82;79;100;108;89;102;100;43;10;83;78;119;107;77;90;121;90;43;51;98;98;86;52;67;52;85;122;121;75;48;104;78;115;117;71;51;82;70;84;75;49;82;67;52;71;77;112;47;80;116;48;105;75;106;120;112;51;75;75;99;72;70;77;114;52;90;89;57;98;87;67;66;47;86;47;116;87;118;83;10;114;43;116;117;98;105;122;122;101;75;90;43;43;53;71;71;102;55;43;56;57;86;67;51;118;49;121;87;109;99;89;106;77;70;67;54;101;84;107;79;106;68;114;109;75;110;115;48;78;51;86;52;68;87;51;122;97;77;106;105;109;69;106;86;116;69;87;111;120;67;10;110;56;117;102;103;89;103;113;51;66;85;73;72;104;75;101;53;53;56;119;103;118;122;98;97;55;75;68;114;97;56;74;48;87;49;102;102;57;99;112;121;68;109;56;89;120;118;83;74;78;50;70;89;116;54;85;76;88;49;47;78;97;67;109;90;66;72;109;114;89;10;82;83;83;105;76;80;73;78;82;103;97;109;67;53;98;74;103;105;70;50;48;47;98;87;105;69;110;68;48;108;122;84;108;119;49;90;88;70;49;86;87;119;77;80;112;87;118;100;97;115;117;119;110;105;65;70;108;101;77;68;55;103;106;82;108;78;84;90;104;85;10;85;65;65;65;100;73;67;55;115;121;109;65;117;55;77;112;103;65;65;65;65;72;99;51;78;111;76;88;74;122;89;81;65;65;65;103;69;65;116;118;121;80;73;68;80;120;115;107;108;120;117;50;83;113;49;54;76;88;50;113;48;54;85;73;122;77;114;67;81;89;10;54;113;122;106;50;98;118;66;106;49;81;97;116;100;69;83;120;122;80;117;97;103;88;65;68;71;52;55;119;84;108;70;101;117;65;43;80;78;104;105;72;75;106;122;88;119;107;43;119;115;49;108;47;67;79;68;43;110;82;75;80;54;109;50;106;69;120;114;87;68;10;106;120;68;89;54;116;65;102;114;65;65;83;100;56;88;119;43;85;106;119;115;75;105;80;78;57;89;48;88;75;116;109;107;118;76;47;56;74;54;52;76;67;69;89;98;108;74;121;50;98;78;106;90;70;120;103;85;119;49;118;49;74;72;105;73;113;54;76;88;70;10;69;65;101;106;81;110;67;79;69;87;101;83;101;84;104;88;75;76;72;49;47;48;84;120;87;48;70;101;106;72;117;99;115;110;68;85;43;114;84;79;74;89;69;107;72;89;51;77;50;113;90;104;72;49;108;114;122;72;80;53;115;89;110;120;107;51;106;55;85;117;10;53;111;68;71;51;115;54;43;72;116;52;48;76;52;80;101;99;101;50;76;112;105;107;99;51;74;82;53;43;68;68;99;47;121;102;87;73;101;74;105;103;118;107;57;119;82;90;85;112;72;54;121;82;51;74;76;90;56;43;80;69;103;112;81;100;43;108;65;56;66;10;47;113;88;66;65;90;43;84;70;106;43;97;55;109;69;100;76;87;100;48;107;102;47;87;48;114;104;102;85;103;104;49;90;110;43;56;84;50;108;65;74;72;49;110;108;97;66;109;74;72;69;106;53;119;104;72;102;118;82;110;68;119;47;116;47;101;87;121;97;98;10;100;90;53;116;48;57;116;85;119;75;119;111;82;79;100;108;89;102;100;43;83;78;119;107;77;90;121;90;43;51;98;98;86;52;67;52;85;122;121;75;48;104;78;115;117;71;51;82;70;84;75;49;82;67;52;71;77;112;47;80;116;48;105;75;106;120;112;51;75;75;10;99;72;70;77;114;52;90;89;57;98;87;67;66;47;86;47;116;87;118;83;114;43;116;117;98;105;122;122;101;75;90;43;43;53;71;71;102;55;43;56;57;86;67;51;118;49;121;87;109;99;89;106;77;70;67;54;101;84;107;79;106;68;114;109;75;110;115;48;78;51;10;86;52;68;87;51;122;97;77;106;105;109;69;106;86;116;69;87;111;120;67;110;56;117;102;103;89;103;113;51;66;85;73;72;104;75;101;53;53;56;119;103;118;122;98;97;55;75;68;114;97;56;74;48;87;49;102;102;57;99;112;121;68;109;56;89;120;118;83;74;78;10;50;70;89;116;54;85;76;88;49;47;78;97;67;109;90;66;72;109;114;89;82;83;83;105;76;80;73;78;82;103;97;109;67;53;98;74;103;105;70;50;48;47;98;87;105;69;110;68;48;108;122;84;108;119;49;90;88;70;49;86;87;119;77;80;112;87;118;100;97;115;10;117;119;110;105;65;70;108;101;77;68;55;103;106;82;108;78;84;90;104;85;85;65;65;65;65;68;65;81;65;66;65;65;65;67;65;66;77;66;103;111;65;117;120;81;68;109;110;102;104;47;121;84;114;105;103;66;99;72;102;82;73;87;118;98;57;51;100;70;115;84;10;111;65;114;105;100;73;86;70;107;65;121;111;98;90;72;104;77;47;99;120;74;55;82;105;48;114;81;77;70;99;112;103;100;106;90;116;112;121;115;103;53;84;53;79;119;73;85;78;80;110;87;69;51;116;86;112;116;76;105;79;69;82;98;98;98;82;55;90;115;122;10;102;99;82;78;51;54;120;71;121;97;82;70;71;47;86;89;102;82;57;115;77;111;118;122;74;76;99;110;87;108;48;83;47;107;66;111;121;43;112;82;101;97;56;106;119;121;103;88;101;78;66;89;119;43;120;56;98;99;119;102;90;117;83;66;83;112;112;74;69;52;10;113;100;49;104;119;87;47;80;87;83;104;99;69;76;108;54;87;110;109;115;71;73;71;73;57;97;65;84;121;114;47;66;57;109;48;102;48;72;87;87;120;48;67;71;108;79;116;48;56;111;117;71;66;121;116;83;78;72;73;98;83;77;115;118;101;114;77;118;98;103;10;69;48;102;98;73;50;89;106;89;68;111;55;77;83;83;87;76;114;89;81;101;82;51;48;69;103;77;85;87;67;47;115;88;70;74;105;113;67;98;65;97;111;105;101;111;67;89;66;118;116;83;113;54;50;103;90;53;57;116;81;49;80;68;80;101;108;52;50;103;109;10;111;84;104;103;56;97;56;83;53;105;50;121;83;111;121;72;118;86;84;89;120;79;66;89;74;66;89;57;77;109;80;106;68;65;105;81;121;56;76;80;70;122;56;103;71;100;112;80;82;110;107;116;89;115;57;51;112;109;51;115;51;79;105;113;109;115;86;116;115;72;10;101;104;78;70;113;90;74;54;114;67;47;49;116;114;53;77;74;71;48;73;75;48;72;99;111;99;77;65;43;111;56;65;78;48;78;109;48;65;107;118;87;56;106;106;43;102;54;100;80;56;75;101;117;77;82;114;50;48;109;102;122;116;106;86;116;57;112;81;105;77;10;122;98;109;98;80;54;105;101;81;119;74;122;103;52;117;55;85;112;54;99;69;111;84;81;81;108;51;70;51;102;43;54;122;115;105;97;106;78;52;55;80;121;79;102;49;68;49;56;66;88;102;71;80;54;49;111;117;52;52;116;88;76;47;51;49;114;72;86;84;89;10;115;70;76;87;87;84;110;49;78;117;72;99;67;72;51;117;76;100;86;86;87;65;99;107;74;78;43;48;82;113;116;86;117;43;49;56;73;120;102;86;87;116;122;55;109;122;119;57;65;72;117;56;97;82;120;49;97;74;107;118;79;70;70;119;73;66;71;118;97;74;10;78;105;90;116;65;108;51;80;56;47;82;85;85;43;50;89;116;69;51;51;122;111;48;66;117;79;112;75;71;106;79;99;43;57;72;117;85;117;55;115;104;115;56;90;106;43;106;52;103;76;78;109;85;107;111;82;52;55;70;110;69;112;47;65;43;66;121;68;98;88;10;118;50;66;101;80;105;102;121;51;74;88;53;57;82;114;75;100;49;65;65;65;66;65;81;68;70;106;98;68;72;107;70;85;118;56;102;70;111;115;118;110;120;56;102;113;85;103;105;106;113;75;103;90;79;79;80;118;103;90;99;87;54;112;56;77;103;109;56;69;102;10;104;120;54;112;80;69;97;113;82;76;47;89;106;65;52;70;77;77;102;106;112;74;110;104;55;47;97;76;67;48;66;68;66;55;77;78;122;100;106;105;109;88;73;103;51;71;54;65;99;87;55;78;82;115;112;117;81;65;110;116;113;53;65;120;112;77;121;56;56;75;10;98;84;85;55;75;112;77;84;53;68;100;72;114;99;85;85;56;110;98;55;75;117;106;117;97;69;87;100;56;100;67;85;122;111;78;86;113;81;108;118;101;106;49;66;56;109;85;67;80;65;75;106;68;77;102;100;80;119;115;98;55;90;121;68;102;76;120;81;104;114;10;116;119;71;111;50;81;78;83;52;101;83;71;67;87;99;116;77;56;118;66;90;82;106;72;70;48;100;54;74;104;71;67;89;115;74;68;120;65;116;121;47;86;101;51;76;121;89;71;43;106;104;49;47;67;76;85;113;51;86;82;117;97;78;56;118;100;116;105;55;112;10;114;56;90;101;117;89;82;81;57;67;109;52;56;43;73;49;75;97;88;76;65;67;66;43;52;81;89;69;108;78;98;76;72;84;113;70;90;75;49;107;50;69;117;102;112;55;77;106;85;72;90;101;115;53;103;115;115;69;120;113;115;98;114;88;85;97;104;90;57;76;10;104;71;90;57;51;109;118;110;83;52;56;71;97;106;101;86;65;65;65;66;65;81;68;90;57;84;116;86;69;68;121;98;51;52;113;97;107;76;88;55;104;102;101;105;86;103;102;79;101;105;43;84;105;47;115;43;110;105;88;104;106;113;69;111;53;49;73;89;51;111;10;98;77;119;111;56;69;57;87;67;65;47;82;84;73;47;56;89;110;89;83;76;47;106;117;104;43;78;43;111;101;89;114;53;83;110;70;82;77;100;106;76;89;110;75;102;75;51;113;68;86;68;109;48;52;65;72;111;74;66;51;79;106;117;51;87;84;111;51;73;65;10;108;66;72;85;109;53;83;85;85;73;49;97;50;99;47;122;71;83;109;50;100;66;50;78;102;120;76;54;67;66;104;122;89;85;51;116;66;83;114;88;56;69;116;118;56;87;83;106;73;79;67;114;118;83;49;113;118;87;43;99;50;71;112;70;100;77;79;118;48;107;10;122;99;55;99;71;86;88;118;57;116;73;74;111;75;105;43;57;67;106;77;121;112;43;66;99;54;97;82;110;75;65;52;87;57;71;71;78;102;89;67;51;122;69;120;90;57;69;54;49;77;49;69;50;121;107;69;85;105;88;78;82;69;72;120;98;54;89;100;56;49;10;99;97;106;43;103;71;77;98;55;57;74;118;110;101;57;68;85;101;47;78;107;104;69;108;103;79;81;109;97;72;80;108;47;77;52;49;114;48;102;113;43;97;100;100;121;100;70;119;68;106;66;112;71;76;121;43;75;50;89;106;80;66;85;90;119;89;43;89;113;50;10;82;43;119;112;110;68;69;114;102;73;86;50;102;106;65;65;65;66;65;81;68;87;55;76;50;105;102;115;54;56;48;85;68;67;105;66;48;86;81;65;43;85;48;102;51;114;89;53;107;53;83;55;70;90;70;90;71;79;99;109;73;48;56;90;75;80;102;114;52;82;10;70;71;70;72;105;71;70;57;117;99;113;56;69;122;89;119;105;97;116;110;71;90;104;52;113;101;104;48;80;48;122;79;117;118;81;119;119;57;121;108;56;114;113;70;79;72;117;108;86;114;104;101;72;69;74;107;71;49;114;89;89;81;70;57;116;106;122;70;100;55;10;107;76;114;77;85;121;71;85;74;99;66;110;81;55;49;100;69;112;47;115;56;118;107;114;56;110;108;118;73;47;111;79;47;72;47;67;56;57;100;107;53;84;114;84;73;47;75;106;90;57;51;76;90;120;107;54;122;52;68;115;113;43;79;56;78;57;122;97;112;89;10;65;107;78;77;71;43;55;106;119;116;102;119;117;84;116;82;71;108;84;74;120;98;43;120;79;50;118;99;107;118;104;108;115;115;84;108;105;89;52;90;115;79;115;116;118;121;98;79;69;74;76;49;106;90;113;49;111;50;65;55;104;120;120;100;80;79;112;104;84;54;10;109;112;70;65;76;82;103;111;100;113;108;119;80;71;53;74;75;54;108;69;68;87;109;75;106;48;104;76;47;71;111;102;81;71;68;57;88;106;71;72;76;81;67;107;79;50;52;81;97;51;68;112;77;98;116;90;54;80;109;105;118;72;99;105;85;84;72;69;115;71;10;112;85;103;82;67;110;102;67;75;70;97;51;65;65;65;65;68;72;100;51;100;121;49;107;89;88;82;104;81;72;66;111;99;65;69;67;65;119;81;70;66;103;61;61;10;45;45;45;45;45;69;78;68;32;79;80;69;78;83;83;72;32;80;82;73;86;65;84;69;32;75;69;89;45;45;45;45;45;10;10","ID":"125"}]}`

and have this

![03792bbf61fa09d9830c0fad2fed8d96](https://github.com/royalapplications/toolbox/assets/134414603/2b2f5192-7b9d-46d7-92e2-551c51b69f17)

I've been fighting for a week, what's wrong?

**Comment by lemonmojo** [comment]
@hostadminonline1 `PrivateKeyMode` and `PrivateKeyContent` are not rJSON properties. The property you're looking for is called `[KeyFileContent](https://docs.royalapps.com/r2023/scripting/rjson/available-properties/royaljsonobject.html#keyfilecontent)` and you're supposed to pass it a plain text string of your key file's contents.

There's no need to set a mode.

Hope that helps!

Cheers,
Felix
